version: "3.1"
services:
  mosquitto:
    build: ./docker_mosquitto
    restart: always
    secrets: 
      - sensitiveInfo
    volumes:
      - conf:/conf
      - logs:/var/log
    ports:
    - "1883:1883"
    - "1884:1884"

  odoo_rfid_mqtt:
    build: ./docker_odoo_rfid_mqtt
    restart: always
    secrets: 
      - sensitiveInfo
    depends_on:
      - mosquitto

networks:
  default:
    driver_opts:
      encrypted: 1

volumes:
  conf:
  logs:

secrets:
  sensitiveInfo:
    file: ./docker_odoo_rfid_mqtt/secrets/sensitiveInfo


